trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: location
    value: 'East US' # Set the default location or change it according to your requirements
  - name: bicepFile
    value: 'Resources/deploy-resources.bicep'

parameters:
  - name: resourceGroupName
    displayName: Resource Group Name
    type: string
    name: subscribtionName
    displayName: Subscribtion
    type: string

steps:
- task: AzureCLI@2
  displayName: 'Install Bicep CLI'
  inputs:
    azureSubscription: '<Your-Azure-Service-Connection>'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64 && chmod +x ./bicep && sudo mv ./bicep /usr/local/bin/bicep'

- task: AzureCLI@2
  displayName: 'Deploy Bicep Template'
  inputs:
    azureSubscription: '<Your-Azure-Service-Connection>'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az group create --name ${{ parameters.resourceGroupName }} --location $(location)
      az deployment group create --resource-group ${{ parameters.resourceGroupName }} --template-file $(bicepFile)
